packages:
  - apps/*
  - packages/*
  - scripts

ignoredBuiltDependencies:
  - sharp
  - unrs-resolver

onlyBuiltDependencies:
  - '@heroui/shared-utils'
  - '@tailwindcss/oxide'
  - '@vscode/vsce-sign'
  - bufferutil
  - cpu-features
  - electron
  - electron-winstaller
  - esbuild
  - keytar
  - protobufjs
  - ssh2
  - utf-8-validate
  - workerd
