[project]
name = "coderouter"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10.0"
dependencies = [
    "morphcloud>=0.1.79",
    "requests>=2.32.4",
]
