/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TerminalsRouteImport } from './routes/terminals'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LayoutSettingsRouteImport } from './routes/_layout.settings'
import { Route as LayoutProfileRouteImport } from './routes/_layout.profile'
import { Route as LayoutDashboardRouteImport } from './routes/_layout.dashboard'
import { Route as LayoutTaskTaskIdRouteImport } from './routes/_layout.task.$taskId'
import { Route as LayoutTaskTaskIdRunTaskRunIdRouteImport } from './routes/_layout.task.$taskId.run.$taskRunId'

const TerminalsRoute = TerminalsRouteImport.update({
  id: '/terminals',
  path: '/terminals',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutSettingsRoute = LayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutProfileRoute = LayoutProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutDashboardRoute = LayoutDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutTaskTaskIdRoute = LayoutTaskTaskIdRouteImport.update({
  id: '/task/$taskId',
  path: '/task/$taskId',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutTaskTaskIdRunTaskRunIdRoute =
  LayoutTaskTaskIdRunTaskRunIdRouteImport.update({
    id: '/run/$taskRunId',
    path: '/run/$taskRunId',
    getParentRoute: () => LayoutTaskTaskIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/terminals': typeof TerminalsRoute
  '/dashboard': typeof LayoutDashboardRoute
  '/profile': typeof LayoutProfileRoute
  '/settings': typeof LayoutSettingsRoute
  '/task/$taskId': typeof LayoutTaskTaskIdRouteWithChildren
  '/task/$taskId/run/$taskRunId': typeof LayoutTaskTaskIdRunTaskRunIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/terminals': typeof TerminalsRoute
  '/dashboard': typeof LayoutDashboardRoute
  '/profile': typeof LayoutProfileRoute
  '/settings': typeof LayoutSettingsRoute
  '/task/$taskId': typeof LayoutTaskTaskIdRouteWithChildren
  '/task/$taskId/run/$taskRunId': typeof LayoutTaskTaskIdRunTaskRunIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_layout': typeof LayoutRouteWithChildren
  '/terminals': typeof TerminalsRoute
  '/_layout/dashboard': typeof LayoutDashboardRoute
  '/_layout/profile': typeof LayoutProfileRoute
  '/_layout/settings': typeof LayoutSettingsRoute
  '/_layout/task/$taskId': typeof LayoutTaskTaskIdRouteWithChildren
  '/_layout/task/$taskId/run/$taskRunId': typeof LayoutTaskTaskIdRunTaskRunIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/terminals'
    | '/dashboard'
    | '/profile'
    | '/settings'
    | '/task/$taskId'
    | '/task/$taskId/run/$taskRunId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/terminals'
    | '/dashboard'
    | '/profile'
    | '/settings'
    | '/task/$taskId'
    | '/task/$taskId/run/$taskRunId'
  id:
    | '__root__'
    | '/'
    | '/_layout'
    | '/terminals'
    | '/_layout/dashboard'
    | '/_layout/profile'
    | '/_layout/settings'
    | '/_layout/task/$taskId'
    | '/_layout/task/$taskId/run/$taskRunId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LayoutRoute: typeof LayoutRouteWithChildren
  TerminalsRoute: typeof TerminalsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terminals': {
      id: '/terminals'
      path: '/terminals'
      fullPath: '/terminals'
      preLoaderRoute: typeof TerminalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/settings': {
      id: '/_layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof LayoutSettingsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/profile': {
      id: '/_layout/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof LayoutProfileRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/dashboard': {
      id: '/_layout/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof LayoutDashboardRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/task/$taskId': {
      id: '/_layout/task/$taskId'
      path: '/task/$taskId'
      fullPath: '/task/$taskId'
      preLoaderRoute: typeof LayoutTaskTaskIdRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/task/$taskId/run/$taskRunId': {
      id: '/_layout/task/$taskId/run/$taskRunId'
      path: '/run/$taskRunId'
      fullPath: '/task/$taskId/run/$taskRunId'
      preLoaderRoute: typeof LayoutTaskTaskIdRunTaskRunIdRouteImport
      parentRoute: typeof LayoutTaskTaskIdRoute
    }
  }
}

interface LayoutTaskTaskIdRouteChildren {
  LayoutTaskTaskIdRunTaskRunIdRoute: typeof LayoutTaskTaskIdRunTaskRunIdRoute
}

const LayoutTaskTaskIdRouteChildren: LayoutTaskTaskIdRouteChildren = {
  LayoutTaskTaskIdRunTaskRunIdRoute: LayoutTaskTaskIdRunTaskRunIdRoute,
}

const LayoutTaskTaskIdRouteWithChildren =
  LayoutTaskTaskIdRoute._addFileChildren(LayoutTaskTaskIdRouteChildren)

interface LayoutRouteChildren {
  LayoutDashboardRoute: typeof LayoutDashboardRoute
  LayoutProfileRoute: typeof LayoutProfileRoute
  LayoutSettingsRoute: typeof LayoutSettingsRoute
  LayoutTaskTaskIdRoute: typeof LayoutTaskTaskIdRouteWithChildren
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutDashboardRoute: LayoutDashboardRoute,
  LayoutProfileRoute: LayoutProfileRoute,
  LayoutSettingsRoute: LayoutSettingsRoute,
  LayoutTaskTaskIdRoute: LayoutTaskTaskIdRouteWithChildren,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LayoutRoute: LayoutRouteWithChildren,
  TerminalsRoute: TerminalsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
