version: '3.8'

services:
  cmux-proxy:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - NODE_ENV=production
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "bun", "-e", "fetch('http://localhost:3000/health').then(r => r.ok || process.exit(1))"]
      interval: 30s
      timeout: 3s
      start_period: 5s
      retries: 3
