version: '3.8'

services:
  cmux-proxy:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PORT=3000
      - NODE_ENV=production
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "bun", "-e", "fetch('http://localhost:3000/health').then(r => r.ok || process.exit(1))"]
      interval: 30s
      timeout: 3s
      start_period: 5s
      retries: 3

  caddy:
    image: caddy:latest
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
    restart: unless-stopped
    depends_on:
      - cmux-proxy
