name: Checks

on:
  push:
    branches: [main]
  pull_request:

jobs:
  verify:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Cache Bun install cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.bun/install/cache
          key: ${{ runner.os }}-bun-install-${{ hashFiles('**/bun.lock') }}
          restore-keys: |
            ${{ runner.os }}-bun-install-

      - name: Use Node.js 24
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Install dependencies
        run: bun install

      - name: Checks and tests (parallel on one runner)
        shell: bash
        run: |
          set -euo pipefail
          bun run check & pid1=$!
          (cd packages/cmux && bun run test) & pid2=$!
          wait $pid1; s1=$?
          wait $pid2; s2=$?
          if [ $s1 -ne 0 ] || [ $s2 -ne 0 ]; then
            echo "At least one task failed"
            exit 1
          fi
