name: Tests (Linux + macOS)

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    name: Run tests on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04, macos-13]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.2.21

      - name: Setup Node.js 24
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Enable Corepack (pnpm)
        run: corepack enable

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Cache Bun install cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.bun/install/cache
          key: ${{ runner.os }}-bun-install-${{ hashFiles('**/bun.lock') }}
          restore-keys: |
            ${{ runner.os }}-bun-install-

      - name: Cache Cargo registry + build
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: |
            apps/server/native/core

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Run tests
        env:
          # Keep default; set to 1 only if you want cross-builds for Linux
          CMUX_BUILD_LINUX: '0'
          # Skip Docker E2E tests in CI for stability/speed
          CMUX_SKIP_DOCKER_TESTS: '1'
        run: bun run test
